pipeline {
    agent {
        docker { image 'python:3-alpine' }
    }
    stages {
        stage('build') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('run') {
            steps {
                sh 'python app.py'
            }
        }
    }
}