pipeline {
  agent {
    kubernetes {
      label 'runner'  // all your pods will be named with this prefix, followed by a unique id
      idleMinutes 5  // how long the pod will live after no jobs have run on it
      yamlFile 'build-pod.yaml'  // path to the pod definition relative to the root of our project 
      defaultContainer 'python'  // define a default container if more than a few stages use it, will default to jnlp container
    }
  }
  
    stages {
        stage('Python runner testing') {
            steps {
                sh 'python -V'
            }
        }

        stage('Build Docker Image') {
            steps {
              container('docker') {  
                sh "docker build -t kanchimo/python-simple-app:$BUILD_NUMBER ."
                sh "docker login -u kanchimo -p credentials('dockerhub_pw')"
                sh "docker push kanchimo/python-simple-app:$BUILD_NUMBER"
              }
            }
        }
    }
}